version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/greenery:z
    restart: always
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greenery
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
      - ./setup/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./setup/data:/data

volumes:
  postgres-data-volume:
